<template>
    <div class=''>
        <h1>css 命名规范</h1>
        <div class="name_text_box">
            <div>1. 内容优先,表现为辅</div>
            <div>2. css命名中英文对照</div>
            <span class="name_text_item" v-for="(text,index) in texts" :key="'css_name'+index">
                <span class="name_text_l">swx_{{text.en}}</span>
                <span class="name_text_r">{{text.ch}}</span>
            </span>
        </div>
    </div>
</template>
<script>
export default {
  data() {
    return {
      texts: [
        { en: "current", ch: "当前" },
        { en: "hover", ch: "悬停" },
        { en: "selected", ch: "挑选" },
        { en: "disabled", ch: "禁用" },
        { en: "focus", ch: "得到焦点" },
        { en: "blur", ch: "失去焦点" },
        { en: "checked", ch: "勾选" },
        { en: "success", ch: "成功" },
        { en: "error", ch: "出错" },
        { en: "header(hd)", ch: "头部" },
        { en: "content(cnt)", ch: "内容" },
        { en: "title(tit)", ch: "标题" },
        { en: "item", ch: "项目（条）" },
        { en: "cell", ch: "单元" },
        { en: "image/pic(img)", ch: "图片" },
        { en: "text(txt)", ch: "文字" },
        { en: "top", ch: "顶部" },
        { en: "scrubber", ch: "时序菜单" },
        { en: "nav", ch: "导航" },
        { en: "mainnav", ch: "主导航" },
        { en: "subnav", ch: "子导航" },
        { en: "topnav", ch: "顶部导航" },
        { en: "breadcrumb", ch: "面包屑导航" },
        { en: "flink", ch: "友情链接" },
        { en: "footer", ch: "尾" },
        { en: "copyright", ch: "版权" },
        { en: "menu", ch: "菜单" },
        { en: "submenu", ch: "子菜单" },
        { en: "dropdown", ch: "下拉菜单" },
        { en: "searchBar", ch: "搜索条" },
        { en: "search", ch: "搜索条" },
        { en: "searchTxt", ch: "搜索框" },
        { en: "searchBtn", ch: "搜索按钮" },
        { en: "search_key", ch: "搜索词" },
        { en: "member", ch: "会员" },
        { en: "ucenter", ch: "用户中心" },
        { en: "loginBar", ch: "登陆条" },
        { en: "login", ch: "登录" },
        { en: "loginBtn", ch: "登录按钮" },
        { en: "regsiter", ch: "注册按钮" },
        { en: "btn-regsiter", ch: "注册按钮" },
        { en: "name", ch: "用户名" },
        { en: "password", ch: "密码" },
        { en: "nickname", ch: "昵称" },
        { en: "mobilephone/mobile", ch: "手机" },
        { en: " telephone/tel", ch: "电话" },
        { en: "defaultavatar", ch: "默认头像" },
        { en: "hot", ch: "热点" },
        { en: "news", ch: "新闻" },
        { en: "banner/AD", ch: "广告" },
        { en: "download", ch: "下载" },
        { en: "content", ch: "内容" },
        { en: "title", ch: "标题" },
        { en: "summary", ch: "摘要" },
        { en: "time", ch: "时间" },
        { en: "share", ch: "分享" },
        { en: "digg", ch: "顶" },
        { en: "like", ch: "喜欢" },
        { en: "list", ch: "列表" },
        { en: "pList", ch: "图片列表" },
        { en: "tList", ch: "文字列表" },
        { en: "tpList", ch: "图文列表" },
        { en: "table", ch: "表格" },
        { en: "row", ch: "行" },
        { en: "column", ch: "列" },
        { en: "gutter", ch: "间隔" },
        { en: "viewport", ch: "视口" },
        { en: "tab", ch: "标签" },
        { en: "tags", ch: "标签" },
        { en: "scroll", ch: "滚动" },
        { en: "sidebar", ch: "侧边栏" },
        { en: "column", ch: "栏目" },
        { en: "section", ch: "区块" },
        { en: "msg", ch: "提示信息" },
        { en: "status", ch: "状态" },
        { en: "vote", ch: "投票" },
        { en: "tips", ch: "小技巧" },
        { en: "guild", ch: "指南" },
        { en: "note", ch: "注释" },
        { en: "icon-", ch: "图标" },
        { en: "btn-", ch: "按钮" },
        { en: "goods", ch: "商品" },
        { en: "goodsList", ch: "商品列表" },
        { en: "goodsDetail", ch: "商品详情" },
        { en: "goodsInfo", ch: "商品信息" },
        { en: "tuan", ch: "团购" },
        { en: "tuanList", ch: "团购列表" },
        { en: "tuanDetail ", ch: "团购详情" },
        { en: "tuanInfo", ch: "团购信息" },
        { en: "transition", ch: "动画" },
        { en: "shadow", ch: "阴影" },
        { en: "fade", ch: "淡入淡出" },
        { en: "flip", ch: "翻页效" },
        { en: "slide", ch: "滑动" },
        { en: "slideup", ch: "上滑动" },
        { en: "slidedown", ch: "下滑动" },
        { en: "turn", ch: "翻页" },
        { en: "horizontal", ch: "水平" },
        { en: "vertical", ch: "垂直" },
        { en: "collapsible", ch: "折叠" },
        { en: "corners", ch: "拐角" },
        { en: "flow", ch: "流" },
        { en: "reverse", ch: "反向" },
        { en: "pop", ch: "弹窗" },
        { en: "count", ch: "总数/计数" },
        { en: "plus", ch: "加号/正" },
        { en: "minus", ch: "减号/负" },
        { en: "controlgroup", ch: "控制组" }
      ]
    };
  }
};
</script>
